# -*- coding: utf-8 -*-
"""nn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SDvX-ZAaXnBY9RvMs32RiPgerD2hiLFA
"""

import torch
import torch.nn as nn

model=nn.Sequential(
    nn.Linear(20,50),
    nn.ReLU(),
    nn.Linear(50,10)
)